services:
  - type: cron
    name: twilio-reminder
    env: docker
    repo: https://github.com/<yourusername>/twilio-reminder
    schedule: "*/2 * * * *"
    startCommand: ./twilio-reminder.sh
    envVars:
      - key: TODOIST_TOKEN
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: TWILIO_TO_NUMBER
        sync: false
